packages:
  - 'tools/*'
  - 'packages/*'
allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@eslint-react/ast@5.12.1'
  - '@eslint-react/core@5.12.1'
  - '@eslint-react/eslint-plugin@5.12.1'
  - '@eslint-react/eslint@5.12.1'
  - '@eslint-react/jsx@5.12.1'
  - '@eslint-react/shared@5.12.1'
  - '@eslint-react/var@5.12.1'
  - eslint-plugin-react-dom@5.12.1
  - eslint-plugin-react-jsx@5.12.1
  - eslint-plugin-react-naming-convention@5.12.1
  - eslint-plugin-react-rsc@5.12.1
  - eslint-plugin-react-web-api@5.12.1
  - eslint-plugin-react-x@5.12.1
